export default [
    {  id: 1,
        name: 'Baguette',
        energie: '265',
        glucide: '59',
        proteines: '8',
        lipides: '1',
      },
      {  id: 2,
        name: 'Tabouna',
        energie: '455',
        glucide: '41',
        proteines: '8',
        lipides: '28',
      },
      {  id: 3,
        name: 'Petit pain',
        energie: '271',
        glucide: '46.07',
        proteines: '8.57',
        lipides: '6.4',
      },
      {  id: 4,
        name: 'Pain aux céréales',
        energie: '265',
        glucide: '43.34',
        proteines: '13.36',
        lipides: '4.23',
      },
      {  id: 5,
        name: 'Pain Complet',
        energie: '296',
        glucide: '50.6',
        proteines: '9',
        lipides: '1.8',
      },
      {  id: 6,
        name: 'pain au son',
        energie: '227',
        glucide: '44.5',
        proteines: '9.5',
        lipides: '1.2',
      },
      {  id: 7,
        name: 'Chocolat Tris',
        energie: '534',
        glucide: '55.6',
        proteines: '8.9',
        lipides: '32.8',
      },
      {  id: 8,
        name: 'Chocolat au lait',
        energie: '544',
        glucide: '56.5',
        proteines: '7.5',
        lipides: '32',
      },
      {  id: 9,
        name: 'Chocolat Noir',
        energie: '745',
        glucide: '68',
        proteines: '60',
        lipides: '39',
      },
      {  id: 10,
        name: 'Beurre',
        energie: '760',
        glucide: '1',
        proteines: '7',
        lipides: '-',
      },
      {  id: 11,
        name: 'Margarine',
        energie: '753',
        glucide: '0.4',
        proteines: '0',
        lipides: '-',
      },
      {  id: 12,
        name: 'Fromage Président',
        energie: '38',
        glucide: '0',
        proteines: '0',
        lipides: '-',
      },
      {  id: 13,
        name: 'Fromage Fraidoux',
        energie: '204',
        glucide: '4',
        proteines: '6',
        lipides: '18',
      },
      {  id: 14,
        name: 'Fromage Jockey',
        energie: '18.4',
        glucide: '3.9',
        proteines: '7.7',
        lipides: '3.4',
      },
      {  id: 15,
        name: 'Fromage Mozzarella',              
        energie: '271',
        glucide: '2',
        proteines: '18.5',
        lipides: '20.9',
      },
      {  id: 16,
        name: 'Fromage blanc nature',
        energie: '75.4', 					
        glucide: '3.68',
        proteines: '7.54',
        lipides: '3.22',
      },
      {  id: 17,
        name: 'Gruyère',
        energie: '412',
        glucide: '0.1',
        proteines: '30',					
        lipides: '32.4',
      },
      {  id: 18,
        name: '',
        energie: '100',
        glucide: '100',
        proteines: '100',
        lipides: '28',
      },
      {  id: 19,
        name: 'Gruyère râpée',                                  
        energie: '389	',
        glucide: '0',
        proteines: '27',
        lipides: '29',
      },
      {  id: 20,
        name: 'Jambon',
        energie: '145',
        glucide: '2',
        proteines: '-',
        lipides: '-',
      },
      {  id: 21,
        name: 'Jambon de dinde/poulet',
        energie: '110',
        glucide: '2',
        proteines: '22',
        lipides: '1.5',
      },
      {  id: 22,
        name: 'Jambon fumé',
        energie: '101',
        glucide: '0.45',
        proteines: '19',
        lipides: '2.59',
      },
      {  id: 23,
        name: 'Salami',
        energie: '482',
        glucide: '1.2',                         
        proteines: '18.1',
        lipides: '45',
      },
      {  id: 24,
        name: 'Salami de dinde',
        energie: '172',
        glucide: '1.5',
        proteines: '19.3',
        lipides: '9.21',
      },
      {  id: 25,
        name: 'Salami de boeuf',
        energie: '258',
        glucide: '1.92',
        proteines: '12.68',
        lipides: '22.34',
      },
    
]