export default [
    {  id: 0,
        name: 'Baguette',
        energie: '265',
        glucide: '59',
        proteines: '8',
        lipides: '1',
        src:"~/assets/images/food/baguette.jpg"
      },
      {  id: 1,
        name: 'Tabouna',
        energie: '455',
        glucide: '41',
        proteines: '8',
        lipides: '28',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 2,
        name: 'Petit pain',
        energie: '271',
        glucide: '46.07',
        proteines: '8.57',
        lipides: '6.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 3,
        name: 'Pain aux céréales',
        energie: '265',
        glucide: '43.34',
        proteines: '13.36',
        lipides: '4.23',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 4,
        name: 'Pain Complet',
        energie: '296',
        glucide: '50.6',
        proteines: '9',
        lipides: '1.8',
        src:"~/assets/images/food/pain-complet.jpg"
      },
      {  id: 5,
        name: 'pain au son',
        energie: '227',
        glucide: '44.5',
        proteines: '9.5',
        lipides: '1.2',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 6,
        name: 'Chocolat Tris',
        energie: '534',
        glucide: '55.6',
        proteines: '8.9',
        lipides: '32.8',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 7,
        name: 'Chocolat au lait',
        energie: '544',
        glucide: '56.5',
        proteines: '7.5',
        lipides: '32',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 8,
        name: 'Chocolat Noir',
        energie: '745',
        glucide: '68',
        proteines: '60',
        lipides: '39',
        src:"~/assets/images/food/chocolat-noir.jpg"
      },
      {  id: 9,
        name: 'Beurre',
        energie: '760',
        glucide: '1',
        proteines: '7',
        lipides: '-',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 10,
        name: 'Margarine',
        energie: '753',
        glucide: '0.4',
        proteines: '0',
        lipides: '-',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 11,
        name: 'Fromage Président',
        energie: '320',
        glucide: '0.18',
        proteines: '9',
        lipides: '31',
        src:"~/assets/images/food/fromage-president.jpg"
      },
      {  id: 12,
        name: 'Fromage Fraidoux',
        energie: '204',
        glucide: '4',
        proteines: '6',
        lipides: '18',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 13,
        name: 'Fromage Jockey',
        energie: '77.1',
        glucide: '3.9',
        proteines: '7.7',
        lipides: '3.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 14,
        name: 'Fromage Mozzarella',              
        energie: '271',
        glucide: '2',
        proteines: '18.5',
        lipides: '20.9',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 15,
        name: 'Fromage blanc nature',
        energie: '75.4', 					
        glucide: '3.68',
        proteines: '7.54',
        lipides: '3.22',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 16,
        name: 'Gruyère',
        energie: '412',
        glucide: '0.1',
        proteines: '30',					
        lipides: '32.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 17,
        name: '',
        energie: '100',
        glucide: '100',
        proteines: '100',
        lipides: '28',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 18,
        name: 'Gruyère râpée',                                  
        energie: '389	',
        glucide: '0',
        proteines: '27',
        lipides: '29',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 19,
        name: 'Jambon',
        energie: '145',
        glucide: '2',
        proteines: '-',
        lipides: '-',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 20,
        name: 'Jambon de dinde/poulet',
        energie: '110',
        glucide: '2',
        proteines: '22',
        lipides: '1.5',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 21,
        name: 'Jambon fumé',
        energie: '101',
        glucide: '0.45',
        proteines: '19',
        lipides: '2.59',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 22,
        name: 'Salami',
        energie: '482',
        glucide: '1.2',                         
        proteines: '18.1',
        lipides: '45',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 23,
        name: 'Salami de dinde',
        energie: '172',
        glucide: '1.5',
        proteines: '19.3',
        lipides: '9.21',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 24,
        name: 'Salami de boeuf',
        energie: '258',
        glucide: '1.92',
        proteines: '12.68',                                     
        lipides: '22.34',
        src:"~/assets/images/home1.jpg"
      },

       {  id: 25,
        name: 'Ricotta',
        energie: '174',
        glucide: '3',
        proteines: '11',                                     
        lipides: '13',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 26,
        name: 'Œuf',
        energie: '145',
        glucide: '0.3',
        proteines: '12.5',                                     
        lipides: '10.5',
        src:"~/assets/images/home1.jpg"
      },
      
      {  id: 27,
        name: 'Yaourt Mamzouj',
        energie: '110',
        glucide: '16.8',
        proteines: '2.9',                                     
        lipides: '-',
        src:"~/assets/images/home1.jpg"
      },
 
       {  id: 28,
        name: 'Yaourt Danette',
        energie: '133.6',
        glucide: '20.4',
        proteines: '3.3',                                     
        lipides: '4.2',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 29,
        name: 'Yaourt nature',
        energie: '65',
        glucide: '2.63',
        proteines: '4.04',                                     
        lipides: '3.9',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 30,
        name: 'Yaourt aux fruits',
        energie: '115',
        glucide: '19.6',
        proteines: '3',                                     
        lipides: '2.7',
        src:"~/assets/images/home1.jpg"
      },
           
       {  id: 31,
        name: 'Yaourt aromatisé',
        energie: '100',
        glucide: '14',
        proteines: '3.2',                                     
        lipides: '3.2',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 32,
        name: 'Yaourt à boire aromatisé',
        energie: '77',
        glucide: '13.3',
        proteines: '2.9',                                     
        lipides: '1.4',
        src:"~/assets/images/home1.jpg"
      },
     
     
     
     
     
     

       {  id: 33,
        name: 'Yaourt à boire pulpe de fruits',
        energie: '78',
        glucide: '13.5',
        proteines: '2.7',                                     
        lipides: '1.6',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 34,
        name: 'Baklawa',
        energie: '461',
        glucide: '49.5',
        proteines: '0',                                     
        lipides: '10.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 35,
        name: 'Couscous aux légumes',
        energie: '40',
        glucide: '5.5',
        proteines: '2',                                     
        lipides: '0.5',
        src:"~/assets/images/home1.jpg"
      },
    
       {  id: 36,
        name: 'Couscous à la viande',
        energie: '152',
        glucide: '17.2',
        proteines: '6.7',                                     
        lipides: '5.8',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 37,
        name: 'Couscous au poulet',
        energie: '158',
        glucide: '17.4',
        proteines: '7.4',                                     
        lipides: '6.22',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 38,
        name: 'Couscous au poisson',
        energie: '114.9',
        glucide: '11.5',
        proteines: '7.4',                                     
        lipides: '4.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 39,
        name: 'Riz Tunisien',
        energie: '615',
        glucide: '10.34',
        proteines: '15.9',                                     
        lipides: '55.6',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 40,
        name: 'Riz blanc',
        energie: '205',
        glucide: '44.5',
        proteines: '4.3',                                     
        lipides: '0.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 41,
        name: 'Plat Kaffteji',
        energie: '864',
        glucide: '19.94',
        proteines: '24.58',                                     
        lipides: '67.35',
        src:"~/assets/images/home1.jpg"
      },
      {  id:42,
        name: 'Lablebi',
        energie: '844',
        glucide: '78.96',
        proteines: '32.16',                                     
        lipides: '42.46',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 43,
        name: 'Cacahuéte',
        energie: '576',
        glucide: '22',
        proteines: '23',                                     
        lipides: '43',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 44,
        name: 'Carottes',
        energie: '40',
        glucide: '8.5',
        proteines: '1',                                     
        lipides: '0',
        src:"~/assets/images/home1.jpg"
      },

       {  id: 45,
        name: 'Caviar',
        energie: '330',
        glucide: '7.5',
        proteines: '30',                                     
        lipides: '20',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 46,
        name: 'Champignons',
        energie: '28',
        glucide: '4.5',
        proteines: '2',                                     
        lipides: '0.3',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 47,
        name: 'Fraise',
        energie: '37',
        glucide: '7.5',
        proteines: '0.7',                                     
        lipides: '0.5',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 48,
        name: 'Poisson grillé',
        energie: '109',
        glucide: '0.28',
        proteines: '22.6',                                     
        lipides: '1.18',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 49,
        name: 'Poisson cuit',
        energie: '154',
        glucide: '4',
        proteines: '18.7',                                     
        lipides: '7',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 50,
        name: 'Poisson frit',
        energie: '199',
        glucide: '15.3',
        proteines: '8.6',                                     
        lipides: '11.3',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 51,
        name: 'Poulet grillé',
        energie: '237',
        glucide: '0',
        proteines: '27.07',                                     
        lipides: '14.49',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 52,
        name: 'Poulet Cuit',
        energie: '120.64',
        glucide: '0',
        proteines: '26.2',                                     
        lipides: '1.72',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 53,
        name: 'Poulet frit',
        energie: '260',
        glucide: '0',
        proteines: '28.62',                                     
        lipides: '15.35',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 54,
        name: 'Escalope frit',
        energie: '111',
        glucide: '0',
        proteines: '28.62',                                     
        lipides: '15.35',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 55,
        name: 'Viande cuite',
        energie: '185',
        glucide: '0',
        proteines: '24.6',                                     
        lipides: '9.7',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 56,
        name: 'Viande grillée',
        energie: '192',
        glucide: '0',
        proteines: '22',                                     
        lipides: '11.5',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 57,
        name: 'Merguez',
        energie: '305',
        glucide: '0',
        proteines: '16',                                     
        lipides: '26.02',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 58,
        name: 'Salade Laitue',
        energie: '14.6',
        glucide: '1.37',
        proteines: '1.3',                                     
        lipides: '0.2',
        src:"~/assets/images/home1.jpg"
      },
      {  id:59,
        name: 'Salade Verte',
        energie: '15.6',
        glucide: '2.31',
        proteines: '0.7',                                     
        lipides: '0.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 60,
        name: 'Salade de riz',
        energie: '151',
        glucide: '2.31',
        proteines: '4.5',                                     
        lipides: '4.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 61,
        name: 'Sandwitch Thon',
        energie: '236.7',
        glucide: '25.9',
        proteines: '12',                                     
        lipides: '9.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 62,
        name: 'Libanais',
        energie: '256.9',
        glucide: '26.9',
        proteines: '6.7',                                     
        lipides: '12.9',
        src:"~/assets/images/home1.jpg"
      },

       {  id: 63,
        name: 'Mayonnaise',
        energie: '762',
        glucide: '0.3',
        proteines: '2',                                     
        lipides: '83.6',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 64,
        name: 'Harissa',
        energie: '75.5',
        glucide: '7.1',
        proteines: '2.7',                                     
        lipides: '2.9',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 65,
        name: 'Ketchup',
        energie: '119',
        glucide: '26.6',
        proteines: '2.25',                                     
        lipides: '0.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 66,
        name: 'Sauce piquante',
        energie: '86',
        glucide: '26.6',
        proteines: '1.3',                                     
        lipides: '6.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 67,
        name: 'Pomme',
        energie: '95',
        glucide: '25.1',
        proteines: '0.5',                                     
        lipides: '0.3',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 68,
        name: 'Banane',
        energie: '134',
        glucide: '34.3',
        proteines: '1.6',                                     
        lipides: '0.5',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 69,
        name: "Huile d'olive",
        energie: '1000',
        glucide: '0',
        proteines: '0',                                     
        lipides: '112.5',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 70,
        name: 'Pomme de terre cuite',
        energie: '82',
        glucide: '20.15',
        proteines: '1.85',                                     
        lipides: '0.2',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 71,
        name: 'Frites',
        energie: '254',
        glucide: '30',
        proteines: '4.6',                                     
        lipides: '12',
        src:"~/assets/images/food/frites.jpg"
      },
      {  id: 72,
        name: 'Puré(de Pomme de terre)',
        energie: '113',
        glucide: '16.94',
        proteines: '1.96',                                     
        lipides: '4.2',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 73,
        name: 'Miel',
        energie: '306.6',
        glucide: '82.66',
        proteines: '0',                                     
        lipides: '0',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 74,
        name: 'Café expresso',
        energie: '4',
        glucide: '0',
        proteines: '0.1',                                     
        lipides: '0.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 75,
        name: 'Café au lait',
        energie: '19',
        glucide: '1.5',
        proteines: '0.9',                                     
        lipides: '1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 76,
        name: 'Café noir',
        energie: '1',
        glucide: '1',
        proteines: '1',                                     
        lipides: '1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 77,
        name: 'Chocolat au lait',
        energie: '83',
        glucide: '10.3',
        proteines: '3.2',                                     
        lipides: '3.4',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 78,
        name: 'Thé vert',
        energie: '1',
        glucide: '0.2',
        proteines: '0.5',                                     
        lipides: '0',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 79,
        name: 'Thé noir',
        energie: '4',
        glucide: '0.5',
        proteines: '0.5',                                     
        lipides: '0',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 80,
        name: 'Thé infusion',
        energie: '0.3',
        glucide: '0',
        proteines: '0.07',                                     
        lipides: '0',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 81,
        name: 'Tisane',
        energie: '1',
        glucide: '0.2',
        proteines: '0',                                     
        lipides: '0',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 82,
        name: 'Nwasser',
        energie: '370',
        glucide: '73',
        proteines: '12',                                     
        lipides: '2',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 83,
        name: 'Mloukhia',
        energie: '239',
        glucide: '12.7',
        proteines: '23',                                     
        lipides: '1.8',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 84,
        name: 'Vermicelle',
        energie: '331',
        glucide: '82',
        proteines: '0.1',                                     
        lipides: '0.1',
        src:"~/assets/images/home1.jpg"
      },
      {  id: 85,
        name: 'Pates',
        energie: '351',
        glucide: '70',
        proteines: '12',                                     
        lipides: '2.5',
        src:"~/assets/images/home1.jpg"
      },
                    

/** */



]